name = "cleaninglady"
main = "src/index.js"
compatibility_date = "2024-08-12"

[vars]
# Add any environment variables here if needed

# Optional: Custom domain setup
[[routes]]
pattern = "clean.djtaxes.win/*"
zone_name = "djtaxes.win"
